# Solution: WEB SCRAPING ASSIGNMENT 4

In [1]:
#importing libraries
import pandas as pd
import re
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as ec
from selenium.common.exceptions import NoSuchElementException, TimeoutException
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys

### Q1. Scrape the details of most viewed videos on YouTube from Wikipedia:
#### Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
**You need to find following details:**

**A) Rank**

**B) Name**

**C) Artist**

**D) Upload date**

**E) Views**

In [2]:
#initializing webdriver with chromedriver
driver = webdriver.Chrome('chromedriver.exe')

#initializing driver with url https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

#initializing most viewed videos on YouTube container
views_container = WebDriverWait(driver,20).until(ec.visibility_of_element_located((By.XPATH,'//table[.//caption[contains(text(),"most-viewed")]]')))

#Scraping required details
ranks = []
names = []
artists = []
upload_dates = []
views = []
record_rows = views_container.find_elements_by_xpath('.//tbody/tr')
for row in record_rows:
    cols = row.find_elements_by_xpath('.//td')
    ranks.append(re.search('\d+',cols[0].text).group(0))
    names.append(re.search('"(.*?)"',cols[1].text).group(1))
    artists.append(cols[2].text)
    upload_dates.append(cols[4].text)
    views.append(cols[3].text)
    

#closing driver
driver.close()

#storing scraped details into dataframe
df_most_viewed_yt_videos = pd.DataFrame({
    "Rank": ranks,
    "Name": names,
    "Artist": artists,
    "Upload Date": upload_dates,
    "Views (billions)": views,
})

#Interpreting scraped details
df_most_viewed_yt_videos

,Rank,Name,Artist,Upload Date,Views (billions)
0,1,Baby Shark Dance,Pinkfong Kids' Songs & Stories,"June 17, 2016",8.44
1,2,Despacito,Luis Fonsi,"January 12, 2017",7.32
2,3,Shape of You,Ed Sheeran,"January 30, 2017",5.29
3,4,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",5.24
4,5,See You Again,Wiz Khalifa,"April 6, 2015",5.08
5,6,Masha and the Bear – Recipe for Disaster,Get Movies,"January 31, 2012",4.43
6,7,Uptown Funk,Mark Ronson,"November 19, 2014",4.16
7,8,Gangnam Style,Psy,"July 15, 2012",4.05
8,9,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",3.97
9,10,Bath Song,Cocomelon – Nursery Rhymes,"May 2, 2018",3.95
10,11,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",3.78
11,12,Sugar,Maroon 5,"January 14, 2015",3.45
12,13,Sorry,Justin Bieber,"October 22, 2015",3.43
13,14,Roar,Katy Perry,"September 5, 2013",3.34
14,15,Dame Tu Cosita,El Chombo,"April 5, 2018",3.28
15,16,Counting Stars,OneRepublic,"May 31, 2013",3.27
16,17,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.24
17,18,Dark Horse,Katy Perry,"February 20, 2014",3.05
18,19,Faded,Alan Walker,"December 3, 2015",3.05
19,20,Shake It Off,Taylor Swift,"August 18, 2014",3.05
20,21,Lean On,Major Lazer Official,"March 22, 2015",3.02
21,22,Bailando,Enrique Iglesias,"April 11, 2014",3.01
22,23,Girls Like You,Maroon 5,"May 31, 2018",3.01
23,24,Let Her Go,Passenger,"July 25, 2012",2.97
24,25,Mi Gente,J Balvin,"June 29, 2017",2.90
25,26,Wheels on the Bus,Cocomelon – Nursery Rhymes,"May 24, 2018",2.89
26,27,Hello,Adele,"October 22, 2015",2.83
27,28,Perfect,Ed Sheeran,"November 9, 2017",2.82
28,29,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",2.80
29,30,Axel F,Crazy Frog,"June 16, 2009",2.77

### Q2. Scrape the details team India’s international fixtures from bcci.tv.
#### Url = https://www.bcci.tv/.
**You need to find following details:**

**A) Match title (I.e. 1st ODI)**

**B) Series**

**C) Place**

**D) Date**

**E) Time**

***Note: - From bcci.tv home page you have reach to the international fixture page through code.***

In [3]:
#initializing webdriver with chromedriver
driver = webdriver.Chrome('chromedriver.exe')

#initializing driver with url https://www.bcci.tv/
driver.get('https://www.bcci.tv')

#Clicking on menu International->Fixtures
international = WebDriverWait(driver,10).until(ec.element_to_be_clickable((By.XPATH,'//li[@data-nav-index="0"]')))
international.click()
international.find_element_by_xpath('.//a[contains(text(),"Fixtures")]').click()

#Intializing infomation container which needs to be scraped
fixture_containers = WebDriverWait(driver,10).until(ec.visibility_of_all_elements_located((By.XPATH,'//div[@class="js-list"]/a')))

#scraping required details
match_titles = []
serieses = []
places = []
dates = []
times = []

for fixture in fixture_containers:
    #scraping match title
    title = fixture.find_element_by_xpath('.//p[@class="fixture__additional-info"]/strong')
    match_titles.append(title.text)
    
    #scraping series
    series = fixture.find_element_by_xpath('.//div[@class="fixture__format-strip"]')
    serieses.append(series.text.replace('\n',' - '))
    
    #scraping place
    place = fixture.find_element_by_xpath('.//p[@class="fixture__additional-info"]/span')
    places.append(place.text)
    
    #scraping date
    day = fixture.find_element_by_xpath('.//span[@class="fixture__day"]')
    month = fixture.find_element_by_xpath('.//span[@class="fixture__month"]')
    date = fixture.find_element_by_xpath('.//span[@class="fixture__date"]')
    dt = f'{day.text}, {date.text} {month.text}'
    dates.append(dt)
    
    #scraping time
    time = fixture.find_element_by_xpath('.//span[@class="fixture__time"]')
    times.append(time.text)
    

#closing driver
driver.close()

#storing scraped data into dataframe
df_fixtures_international = pd.DataFrame({
    "Match Title": match_titles,
    "Series": serieses,
    "Place": places,
    "Date": dates,
    "Time": times,
})

#Interpreting scraped data
df_fixtures_international

,Match Title,Series,Place,Date,Time
0,Final,TEST - ICC WORLD TEST CHAMPIONSHIP FINAL,"The Ageas Bowl, Southampton","Friday, 18 JUNE",15:30 IST
1,1st Test,TEST - ENGLAND V INDIA 2021,"Trent Bridge, Nottingham","Wednesday, 04 AUGUST",15:30 IST
2,2nd Test,TEST - ENGLAND V INDIA 2021,"Lord's, London","Thursday, 12 AUGUST",15:30 IST
3,3rd Test,TEST - ENGLAND V INDIA 2021,"Headingley, Leeds","Wednesday, 25 AUGUST",15:30 IST
4,4th Test,TEST - ENGLAND V INDIA 2021,"The Oval, London","Thursday, 02 SEPTEMBER",15:30 IST
5,5th Test,TEST - ENGLAND V INDIA 2021,"Old Trafford, Manchester","Friday, 10 SEPTEMBER",15:30 IST

### Q3. Scrape the details of selenium exception from guru99.com.
#### Url = https://www.guru99.com/
**You need to find following details:**

**A) Name**

**B) Description**

***Note: - From guru99 home page you have to reach to selenium exception handling page through code.***

In [4]:
#initializing webdriver with chromedriver
driver = webdriver.Chrome('chromedriver.exe')

#initializing driver with url https://www.guru99.com
driver.get('https://www.guru99.com')

#clicking on selenium exception handling page ie. testing->selenium->selenium exception handling
#WebDriverWait(driver,10).until(ec.element_to_be_clickable((By.XPATH,'//span[@class="g-menu-item-title" and contains(text(),"Testing")]'))).click()
elem = driver.find_element_by_xpath('//nav[@class="g-main-nav"]/ul/li[2]')
ActionChains(driver).move_to_element(elem).perform()
WebDriverWait(driver,20).until(ec.element_to_be_clickable((By.XPATH,'//span[@class="g-menu-item-title" and contains(text(),"Selenium")]'))).click()

#searching for selenium exception handling and clicking on it
WebDriverWait(driver,10).until(ec.element_to_be_clickable((By.XPATH,'//td[contains(text(),"Selenium Exception Handling")]/preceding-sibling::td/a'))).click()

#scraping required details
names = []
descriptions = []

exception_containers = driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr')

for exception in exception_containers[1:]:
    cols = exception.find_elements_by_xpath('.//td')
    names.append(cols[0].text)
    descriptions.append(cols[1].text)
    

#closing driver
driver.close()

#storing records into dataframe
df_exceptions = pd.DataFrame({
    "Name": names,
    "Description": descriptions,
})

#Interpreting exceptions details
df_exceptions

,Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can't be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

### Q4. Scrape the details of State-wise GDP of India from statisticstime.com.
#### Url = http://statisticstimes.com/
**You have to find following details:**

**A) Rank**

**B) State**

**C) GSDP(18-19)**

**D) GSDP(17-18)**

**E) Share(2017)**

**F) GDP($ billion)**

***Note: - From statisticstimes home page you have to reach to economy page through code.***

In [5]:
#initializing webdriver with chromedriver
driver = webdriver.Chrome('chromedriver.exe')

#initializing driver with url http://statisticstimes.com
driver.get('http://statisticstimes.com')

#clickig on economy -> india
WebDriverWait(driver,3).until(ec.element_to_be_clickable((By.XPATH,'//button[@class="dropbtn" and contains(text(),"Economy")]'))).click()
WebDriverWait(driver,3).until(ec.element_to_be_clickable((By.XPATH,'//button[@class="dropbtn" and contains(text(),"Economy")]/following-sibling::div/a[contains(text(),"India")]'))).click()

#manually close the ad pop-up

#clicking on link GDP of Indian States
WebDriverWait(driver,10).until(ec.element_to_be_clickable((By.XPATH,'//a[contains(text(),"GDP of Indian states")]'))).click()

#initializing information container
gdp_containers = driver.find_elements_by_xpath('//table[@id="table_id"]/tbody/tr')

#scraping required data
ranks = []
states = []
gsdp_19_20 = []
gsdp_18_19 = []
shares = []
gdp_billions = []

for gdp in gdp_containers:
    cols = gdp.find_elements_by_xpath('.//td')
    
    #scraping rank
    ranks.append(cols[0].text)
    
    #scraping state
    states.append(cols[1].text)
    
    #scraping GSDP (19-20)
    gsdp_19_20.append(cols[2].text)
    
    #scraping GSDP (18-19)
    gsdp_18_19.append(cols[3].text)
    
    #scraping Share
    shares.append(cols[4].text)
    
    #scraping GDP ($billion)
    gdp_billions.append(cols[5].text)
    
    
#closing driver
driver.close()

#storing scraped data into dataframe
df_gdp_indian_states = pd.DataFrame({
    "Rank": ranks,
    "State": states,
    "GSDP (19-20)": gsdp_19_20,
    "GSDP (18-19)": gsdp_18_19,
    "Share (18-19)": shares,
    "GDP ($billion)": gdp_billions,
})

#interpreting scraped gdp data
df_gdp_indian_states

,Rank,State,GSDP (19-20),GSDP (18-19),Share (18-19),GDP ($billion)
0,1,Maharashtra,-,"2,632,792",13.88%,398.145
1,2,Tamil Nadu,"1,845,853","1,630,208",8.59%,246.529
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.35%,239.656
3,4,Gujarat,-,"1,502,899",7.92%,227.276
4,5,Karnataka,"1,631,977","1,493,127",7.87%,225.798
5,6,West Bengal,"1,253,832","1,089,898",5.75%,164.820
6,7,Rajasthan,"1,020,989","942,586",4.97%,142.543
7,8,Andhra Pradesh,"972,782","862,957",4.55%,130.501
8,9,Telangana,"969,604","861,031",4.54%,130.210
9,10,Madhya Pradesh,"906,672","809,592",4.27%,122.431
10,11,Kerala,-,"781,653",4.12%,118.206
11,12,Delhi,"856,112","774,870",4.08%,117.180
12,13,Haryana,"831,610","734,163",3.87%,111.024
13,14,Bihar,"611,804","530,363",2.80%,80.204
14,15,Punjab,"574,760","526,376",2.77%,79.601
15,16,Odisha,"521,275","487,805",2.57%,73.768
16,17,Assam,-,"315,881",1.67%,47.769
17,18,Chhattisgarh,"329,180","304,063",1.60%,45.982
18,19,Jharkhand,"328,598","297,204",1.57%,44.945
19,20,Uttarakhand,-,"245,895",1.30%,37.186
20,21,Jammu & Kashmir,-,"155,956",0.82%,23.584
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.265
22,23,Goa,"80,449","73,170",0.39%,11.065
23,24,Tripura,"55,984","49,845",0.26%,7.538
24,25,Chandigarh,-,"42,114",0.22%,6.369
25,26,Puducherry,"38,253","34,433",0.18%,5.207
26,27,Meghalaya,"36,572","33,481",0.18%,5.063
27,28,Sikkim,"32,496","28,723",0.15%,4.344
28,29,Manipur,"31,790","27,870",0.15%,4.215
29,30,Nagaland,-,"27,283",0.14%,4.126
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.721
31,32,Mizoram,"26,503","22,287",0.12%,3.370
32,33,Andaman & Nicobar Islands,-,-,-,-

### Q5. Scrape the details of trending repositories on Github.com.
#### Url = https://github.com/
**You have to find the following details:**
    
**A) Repository title**

**B) Repository description**

**C) Contributors count**

**D) Language used**

***Note: - From the home page you have to click on the trending option from Explore menu through code.***

In [6]:
#initializing webdriver with chromedriver
driver = webdriver.Chrome('chromedriver.exe')

#initializing driver with url https://github.com
driver.get('https://github.com')

#clicking on explore
explore = WebDriverWait(driver,5).until(ec.element_to_be_clickable((By.XPATH,'//summary[contains(text(),"Explore")]')))
ActionChains(driver).move_to_element(explore).perform() #hovering over explore menu
explore.click()
#clicking on trending
WebDriverWait(driver,5).until(ec.element_to_be_clickable((By.XPATH,'//li/a[contains(text(),"Trending")]'))).click()

#initializing trending repository containers
repository_containers = driver.find_elements_by_xpath('//article[@class="Box-row"]')

#storing original window handle
original_window = driver.current_window_handle

#scraping required details
repository_titles = []
repository_descriptions = []
contributor_counts = []
languages_used = []
for repo in repository_containers:
    #scraping repository title
    try:
        title = repo.find_element_by_xpath('.//h1/a')
        repository_titles.append(title.text)
    except NoSuchElementException:
        repository_titles.append('-')
        
    #scraping repository description
    try:
        description = repo.find_element_by_xpath('.//p')
        repository_descriptions.append(description.text)
    except NoSuchElementException:
        repository_descriptions.append('-')
        
    #scraping languages used
    try:
        language = repo.find_element_by_xpath('.//span[@itemprop="programmingLanguage"]')
        languages_used.append(language.text)
    except NoSuchElementException:
        languages_used.append('-')
        
    #scraping contributors count
    try:
        title.send_keys(Keys.CONTROL + Keys.ENTER)
        driver.switch_to.window(driver.window_handles[-1])
        contributor = WebDriverWait(driver,10).until(ec.element_to_be_clickable((By.XPATH,'//a[contains(text(),"Contributors")]/span[@class="Counter "]')))
        contributor_counts.append(contributor.text)
        
        driver.close()
        driver.switch_to.window(original_window)
    except TimeoutException:
        contributor_counts.append('-')
        driver.close()
        driver.switch_to.window(original_window)
        
        
#closing driver
driver.close()

#storing scraped data into dataframe
df_trending_repositories = pd.DataFrame({
    "Repository Title": repository_titles,
    "Repository Description": repository_descriptions,
    "Contributor Counts": contributor_counts,
    "Language Used": languages_used,
})

#interpreting scraped data
df_trending_repositories

,Repository Title,Repository Description,Contributor Counts,Language Used
0,supabase / supabase,The open source Firebase alternative. Follow t...,91,TypeScript
1,livewire / livewire,A full-stack framework for Laravel that takes ...,160,Blade
2,johnBuffer / NoCol,Trajectories finder,3,C++
3,521xueweihan / HelloGitHub,分享 GitHub 上有趣、入门级的开源项目,11,Python
4,Developer-Y / cs-video-courses,List of Computer Science courses with video le...,44,-
5,PaddlePaddle / PaddleDetection,Object detection and instance segmentation too...,55,Python
6,nextapps-de / winbox,WinBox is a professional HTML5 window manager ...,-,JavaScript
7,UnityTechnologies / open-project-1,Unity Open Project #1: Chop Chop,83,C#
8,flashlight / flashlight,A C++ standalone library for machine learning,45,C++
9,TheAlgorithms / Python,All Algorithms implemented in Python,683,Python
10,dani-garcia / vaultwarden,Unofficial Bitwarden compatible server written...,71,Rust
11,nvbn / thefuck,Magnificent app which corrects your previous c...,156,Python
12,trekhleb / javascript-algorithms,📝 Algorithms and data structures implemented i...,139,JavaScript
13,doocs / leetcode,😏 LeetCode solutions in any programming langua...,68,Java
14,mlflow / mlflow,Open source platform for the machine learning ...,295,Python
15,xinliangnote / go-gin-api,基于 Gin 进行模块化设计的 API 框架，封装了常用功能，使用简单，致力于进行快速的业务...,-,Go
16,gitflai / Semana-do-Iniciante-em-Data-Science,-,-,-
17,tensorflow / tensorboard,TensorFlow's Visualization Toolkit,187,TypeScript
18,SagerNet / SagerNet,The universal proxy toolchain for Android.,6,Kotlin
19,commaai / openpilot,openpilot is an open source driver assistance ...,174,C++
20,chrisleekr / binance-trading-bot,Automated Binance trading bot - Buy low/Sell h...,5,JavaScript
21,storj / drpc,"drpc is a lightweight, drop-in replacement for...",6,Go
22,airbnb / lottie-ios,An iOS library to natively render After Effect...,143,Swift
23,seek-oss / vanilla-extract,Zero-runtime Stylesheets-in-TypeScript,9,TypeScript
24,huggingface / datasets,🤗 The largest hub of ready-to-use NLP datasets...,267,Python

### Q6. Scrape the details of top 100 songs on billiboard.com.
#### Url = https://www.billboard.com/
**You have to find the following details:**

**A) Song name**

**B) Artist name**

**C) Last week rank**

**D) Peak rank**

**E) Weeks on board**

***Note: - From the home page you have to click on the charts option then hot 100-page link through code***

In [7]:
#intializing webdriver with chromedriver
driver = webdriver.Chrome('chromedriver.exe')

#initializing driver with url https://www.billboard.com/
driver.get('https://www.billboard.com')

#intializing the CHARTS menu
containers = driver.find_elements_by_xpath("//li/a[normalize-space(text()) = 'Charts']")
for x in containers:
    if x.text == "CHARTS":
        chart = x
        break
        
#hovering over chart menu
ActionChains(driver).move_to_element(chart).perform()

#initializing and clicking on hot 100 link
hot_100 = driver.find_elements_by_xpath('//a[@data-track-action="main-nav" and text()="Hot 100"]')
hot_100[1].click()

#initializing top 100 songs containers
song_containers = WebDriverWait(driver,10).until(ec.presence_of_all_elements_located((By.XPATH,'//ol[@class="chart-list__elements"]/li')))

#scraping song details
song_names = []
artist_names = []
last_week_ranks = []
peak_ranks = []
weeks_on_boards = []
for song in song_containers:
    #scraping song name
    try:
        song_name = song.find_element_by_xpath('.//span[@class="chart-element__information__song text--truncate color--primary"]')
        song_names.append(song_name.text)
    except NoSuchElementException:
        song_names.append('-')
        
    #scraping artist name
    try:
        artist_name = song.find_element_by_xpath('.//span[@class="chart-element__information__artist text--truncate color--secondary"]')
        artist_names.append(artist_name.text)
    except NoSuchElementException:
        artist_names.append('-')
        
    #scraping last week rank
    try:
        last_week_rank = song.find_element_by_xpath('.//div[@class="chart-element__meta text--center color--secondary text--last"]')
        last_week_ranks.append(last_week_rank.text)
    except NoSuchElementException:
        last_week_ranks.append(last_week_rank.text)
        
    #scraping peak rank
    try:
        peak_rank = song.find_element_by_xpath('.//div[@class="chart-element__meta text--center color--secondary text--peak"]')
        peak_ranks.append(peak_rank.text)
    except NoSuchElementException:
        peak_ranks.append('-')
        
    #scraping weeks on board
    try:
        weeks_on_board = song.find_element_by_xpath('.//div[@class="chart-element__meta text--center color--secondary text--week"]')
        weeks_on_boards.append(weeks_on_board.text)
    except:
        weeks_on_boards.append('-')
        
        
#closing driver
driver.close()

#storing scraped data into dataframe
df_top_100_songs = pd.DataFrame({
    "Song Name": song_names,
    "Artist Name": artist_names,
    "Last Week Rank": last_week_ranks,
    "Peak Rank": peak_ranks,
    "Weeks on Board": weeks_on_boards,
})

#interpreting scraped data
df_top_100_songs

,Song Name,Artist Name,Last Week Rank,Peak Rank,Weeks on Board
0,Rapstar,Polo G,1,1,2
1,Leave The Door Open,Silk Sonic (Bruno Mars & Anderson .Paak),3,1,7
2,Peaches,Justin Bieber Featuring Daniel Caesar & Giveon,4,1,5
3,Montero (Call Me By Your Name),Lil Nas X,2,1,4
4,Levitating,Dua Lipa Featuring DaBaby,6,5,29
...,...,...,...,...,...
104,Go!,Moneybagg Yo Featuring BIG30,-,96,1
105,Drankin N Smokin,Future & Lil Uzi Vert,-,31,12
106,Monsters,All Time Low Featuring Demi Lovato & blackbear,95,55,17
107,Slatty,Young Thug & Gunna Featuring Yak Gotti & Lil Duke,-,99,1
108,4 Da Gang,42 Dugg & Roddy Ricch,84,67,3

### Q7. Scrape the details of Data science recruiters from naukri.com.
#### Url = https://www.naukri.com/
**You have to find the following details:**
    
**A) Name**

**B) Designation**

**C) Company**

**D) Skills they hire for**

**E) Location**

***Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code***

In [8]:
#initializing webdriver with chromedriver
driver = webdriver.Chrome('chromedriver.exe')

#initializing driver with url https://www.naukri.com
driver.get('https://www.naukri.com')

#clicking on recruiters option
WebDriverWait(driver,10).until(ec.element_to_be_clickable((By.XPATH,'//li/a[@title="Search Recruiters"]'))).click()

#storing current window handle and switching to new opened window
original_window = driver.current_window_handle
driver.switch_to.window(driver.window_handles[-1])

#initializing search box with Data science
driver.find_element_by_xpath('//input[@name="qp"]').send_keys('Data science')

#clicking on search button
driver.find_element_by_xpath('//button[@id="qsbFormBtn"]').click()

#initializing recruiter containers
recruiter_containers = WebDriverWait(driver,10).until(ec.presence_of_all_elements_located((By.XPATH,'//div[@id="tabP-1"]/div[@class="outerRecSec"]')))

#scraping the required details
names = []
designations = []
companies = []
skills_they_hires = []
locations = []
for recruiter in recruiter_containers:
    cols = recruiter.find_elements_by_class_name('recSec')
    for col in cols:
        #scraping name
        try:
            name = col.find_element_by_xpath('.//span[@class="fl ellipsis"]')
            names.append(name.text)
        except NoSuchElementException:
            names.append('-')
            
        #scraping designation
        try:
            designation = col.find_element_by_xpath('.//span[@class="ellipsis clr"]')
            designations.append(designation.text)
        except NoSuchElementException:
            designations.append('-')
            
        #scraping company
        try:
            company = col.find_element_by_xpath('.//a[@class="ellipsis"][2]')
            companies.append(company.text)
        except NoSuchElementException:
            companies.append('-')
            
        #scraping skills they hire for
        try:
            skills = col.find_element_by_xpath('.//div[@class="hireSec highlightable"]')
            skills_they_hires.append(skills.text)
        except NoSuchElementException:
            skills_they_hires.append('-')
            
        #scraping location
        try:
            location = col.find_element_by_xpath('.//small[@class="ellipsis"]')
            locations.append(location.text)
        except NoSuchElementException:
            locations.append('-')
            
#closing driver
driver.close()
driver.switch_to.window(original_window)
driver.close()

#storing scraped data into dataframe
df_recruiters = pd.DataFrame({
    "Name": names,
    "Designation": designations,
    "Company": companies,
    "Skills They Hire For": skills_they_hires,
    "Location": locations,
})

#interpreting scraped data
df_recruiters

,Name,Designation,Company,Skills They Hire For,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,Talent Acquisition Executive,Recruitment Professional,XenonStack,"Web Designing, html5, Angular.js, seo, hadoop,...",Chandigarh
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
5,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
6,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
7,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
8,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
9,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
10,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
12,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
14,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Nagpur
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
16,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
17,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
18,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
19,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
20,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
21,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
22,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
23,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
25,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
27,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",-
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Delhi
30,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
31,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Hyderabad / Secunderabad
32,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Testing, Mac...",Noida
33,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",New Delhi
34,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Chennai
35,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Aligarh
36,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Salt Lake City
37,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Pune
38,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
39,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Mumbai
40,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Indore
41,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Bengaluru / Bangalore
42,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",MYSORE
43,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
44,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
45,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Mumbai
46,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",-
47,Shailja Mishra,HR Manager,Certybox Pvt.Ltd.,"consulting, Education Counseling, Educational ...",Noida
48,Sunny Sharma,Managing Director - HR,Western Service Providers,"Software Professionals, Engineering, Technical...",Mumbai
49,Sagar Lama,Company HR Manager,AdView,"Full Stack Developers, Product Manager, Data S...",Bengaluru / Bangalore

### Q8. Scrape the details of Highest selling novels.
#### Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/

**You have to find the following details:**
    
**A) Book name**

**B) Author name**

**C) Volumes sold**

**D) Publisher**

**E) Genre**

In [9]:
#initializing webdriver with chromedriver
driver = webdriver.Chrome('chromedriver.exe')

#initializing driver with url https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')

#initializing novel containers
novel_containers = WebDriverWait(driver,10).until(ec.presence_of_all_elements_located((By.XPATH,'//table[@class="in-article sortable"]/tbody/tr')))

#scraping required details
book_names = []
author_names = []
volume_solds = []
publishers = []
genres = []

for novel in novel_containers:
    cols = novel.find_elements_by_xpath('.//td')
    
    #scraping book name
    try:
        book_names.append(cols[1].text)
    except NoSuchElementException:
        book_names.append('-')
        
    #scraping author name
    try:
        author_names.append(cols[2].text)
    except NoSuchElementException:
        author_names.append('-')
        
    #scraping volumes sold
    try:
        volume_solds.append(cols[3].text)
    except NoSuchElementException:
        volume_solds.append('-')
        
    #scraping publishers
    try:
        publishers.append(cols[4].text)
    except NoSuchElementException:
        publishers.append('-')
        
    #scraping genres
    try:
        genres.append(cols[5].text)
    except NoSuchElementException:
        genres.append('-')
        
#closing driver
driver.close()

#storing scraped data into dataframe
df_highest_selling_novels = pd.DataFrame({
    "Book Name": book_names,
    "Author Name": author_names,
    "Volumes Sold": volume_solds,
    "Publisher": publishers,
    "Genre": genres,
})

#interpreting scraped data
df_highest_selling_novels

,Book Name,Author Name,Volumes Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

### Q9. Scrape the details most watched tv series of all time from imdb.com.
#### Url = https://www.imdb.com/list/ls095964455/
**You have to find the following details:**
    
**A) Name**

**B) Year span**

**C) Genre**

**D) Run time**

**E) Ratings**

**F) Votes**

In [10]:
#initializing webdriver with chromedriver
driver = webdriver.Chrome('chromedriver.exe')

#initializing driver with url https://www.imdb.com/list/ls095964455/
driver.get('https://www.imdb.com/list/ls095964455/')

#initializing most watched tv series containers
series_containers = WebDriverWait(driver,10).until(ec.presence_of_all_elements_located((By.XPATH,'//div[@class="lister-item-content"]')))

#scraping required details
names = []
year_spans = []
genres = []
run_times = []
ratings = []
votes = []

for series in series_containers:
    #scraping name
    try:
        name = series.find_element_by_xpath('.//h3[@class="lister-item-header"]/a')
        names.append(name.text)
    except NoSuchElementException:
        names.append('-')
        
    #scraping year span
    try:
        year_span = series.find_element_by_xpath('.//span[@class="lister-item-year text-muted unbold"]')
        year_spans.append(year_span.text)
    except NoSuchElementException:
        year_spans.append('-')
        
    #scraping genre
    try:
        genre = series.find_element_by_xpath('.//span[@class="genre"]')
        genres.append(genre.text)
    except NoSuchElementException:
        genres.append('-')
        
    #scraping run time
    try:
        run_time = series.find_element_by_xpath('.//span[@class="runtime"]')
        run_times.append(run_time.text)
    except NoSuchElementException:
        run_times.append('-')
        
    #scraping rating
    try:
        rating = series.find_element_by_xpath('.//span[@class="ipl-rating-star__rating"]')
        ratings.append(rating.text)
    except NoSuchElementException:
        ratings.append('-')
        
    #scraping vote
    try:
        vote = series.find_element_by_xpath('.//span[@name="nv"]')
        votes.append(vote.text)
    except NoSuchElementException:
        votes.append('-')
        
#closing driver
driver.close()

#storing scraped data into dataframe
df_most_watched_tv_series = pd.DataFrame({
    "Name": names,
    "Year Span": year_spans,
    "Genre": genres,
    "Run Time": run_times,
    "Ratings": ratings,
    "Votes": votes,
})

#interpreting scraped data
df_most_watched_tv_series

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.3,"1,801,079"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"846,490"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"867,286"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"260,013"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"220,969"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"44,188"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"54,639"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"165,285"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.2,"34,551"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"187,899"

### Q10. Details of Datasets from UCI machine learning repositories.
#### Url = https://archive.ics.uci.edu/
**You have to find the following details:**
    
**A) Dataset name**

**B) Data type**

**C) Task**

**D) Attribute type**

**E) No of instances**

**F) No of attribute**

**G) Year**

**Note: - from the home page you have to go to the Show All Dataset page through code**

In [11]:
#initializing webdriver with chromedriver
driver = webdriver.Chrome('chromedriver.exe')

#initializing driver with url https://archive.ics.uci.edu/
driver.get('https://archive.ics.uci.edu')

#click on link view all data sets
WebDriverWait(driver,10).until(ec.element_to_be_clickable((By.XPATH,'//b[contains(text(),"View ALL Data Sets")]'))).click()

#initializing dataset containers
dataset_containers = WebDriverWait(driver,10).until(ec.presence_of_all_elements_located((By.XPATH,'//body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr')))

#scraping required details
names = []
data_types = []
tasks = []
attribute_types = []
instances = []
attributes = []
years = []

for dataset in dataset_containers[1:]:
    cols = dataset.find_elements_by_xpath('./td')
    
    #scraping dataset name
    try:
        names.append(cols[0].text.strip())
    except NoSuchElementException:
        names.append('-')
        
    #scraping data types
    try:
        data_types.append(cols[1].text.strip())
    except NoSuchElementException:
        data_types.append('-')
        
    #scraping task
    try:
        tasks.append(cols[2].text.strip())
    except NoSuchElementException:
        tasks.append('-')
        
    #scraping attribute types
    try:
        attribute_types.append(cols[3].text.strip())
    except NoSuchElementException:
        attribute_types.append('-')
        
    #scraping number of instances
    try:
        instances.append(cols[4].text.strip())
    except NoSuchElementException:
        instances.append('-')
        
    #scraping number of attributes
    try:
        attributes.append(cols[5].text.strip())
    except NoSuchElementException:
        attributes.append('-')
        
    #scraping year
    try:
        years.append(cols[6].text.strip())
    except NoSuchElementException:
        years.append('-')

#closing driver
driver.close()

#storing scraped data in dataframe
df_datasets = pd.DataFrame({
    "Dataset Name": names,
    "Data Types": data_types,
    "Task": tasks,
    "Atrribute Types": attribute_types,
    "No. of Instances": instances,
    "No. of Attributes": attributes,
    "Year": years,
})

#interpreting scraped data
df_datasets

,Dataset Name,Data Types,Task,Atrribute Types,No. of Instances,No. of Attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
580,Wisesight Sentiment Corpus,"Multivariate, Text",Classification,,26737,4,2020
581,AI4I 2020 Predictive Maintenance Dataset,"Multivariate, Time-Series","Classification, Regression, Causal-Discovery",Real,10000,14,2020
582,Dry Bean Dataset,Multivariate,Classification,"Integer, Real",13611,17,2020
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020

End of Web Scraping Assignment 4|
----------------------------------------------------|